language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
cache: pip
addons:
  ssh_known_hosts: 157.230.188.74
before_install:
- openssl aes-256-cbc -K $encrypted_92725ca94bf5_key -iv $encrypted_92725ca94bf5_iv
  -in docs/deploy-key.enc -out docs/deploy-key -d
install:
- pip install sphinx sphinx_rtd_theme
- pip install --verbose --editable .
after_success:
- bash docs/deploy_script.sh
